"""
AuthService — demonstrates the Salt + Pepper password strategy.

┌─────────────────────────────────────────────────────────────┐
│  SALT + PEPPER STRATEGY                                     │
│                                                             │
│  Pepper  → server-side secret (PASSWORD_PEPPER env var)     │
│            never stored in the database                     │
│            protects against DB-only breaches                │
│                                                             │
│  Salt    → random value generated by bcrypt automatically   │
│            embedded inside the stored hash string           │
│            protects against rainbow table attacks           │
│                                                             │
│  Flow:                                                      │
│    register: password + pepper ──► bcrypt(+auto-salt) ──► hash │
│    login:    password + pepper ──► bcrypt.verify(hash)      │
└─────────────────────────────────────────────────────────────┘
"""

from passlib.context import CryptContext
from fastapi import HTTPException, status

from ..models.user import User
from ..repositories.user_repository import UserRepository
from ..core.jwt import create_access_token
from ..core.config import settings

_pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def _hash_password(plain: str) -> str:
    """Pepper is added BEFORE bcrypt hashing. bcrypt then auto-generates the salt."""
    return _pwd_context.hash(plain + settings.PASSWORD_PEPPER)


def _verify_password(plain: str, hashed: str) -> bool:
    """Re-add pepper then let bcrypt verify (which also checks the embedded salt)."""
    return _pwd_context.verify(plain + settings.PASSWORD_PEPPER, hashed)


class AuthService:
    def __init__(self, repo: UserRepository):
        self.repo = repo

    def register(self, name: str, email: str, password: str) -> User:
        # Business rule: duplicate email check
        if self.repo.get_by_email(email):
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Email already registered",
            )

        user = User(
            name=name,
            email=email,
            hashed_password=_hash_password(password),  # salt+pepper applied here
        )
        return self.repo.create(user)

    def login(self, email: str, password: str) -> tuple[User, str]:
        user = self.repo.get_by_email(email)
        if not user or not _verify_password(password, user.hashed_password):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid email or password",
                headers={"WWW-Authenticate": "Bearer"},
            )

        token = create_access_token(
            user_id=user.id,
            email=user.email,
            name=user.name,
        )
        return user, token
