"""
JWT utility — token creation and decoding.

Salt + Pepper strategy (enforced in auth_service.py):
  - Pepper : server-side secret from PASSWORD_PEPPER env var (never stored in DB)
  - Salt   : randomly generated by bcrypt and embedded inside the hash string
  - Flow   : plain_password + pepper  ──►  bcrypt(auto-salt)  ──►  stored_hash

This file handles only the JWT side (issue + verify tokens).
"""

from datetime import datetime, timedelta, timezone
from typing import Optional

from jose import JWTError, jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials

from .config import settings

_bearer_scheme = HTTPBearer()


def create_access_token(user_id: str, email: str, name: str) -> str:
    expire = datetime.now(timezone.utc) + timedelta(minutes=settings.JWT_EXPIRE_MINUTES)
    payload = {
        "sub": user_id,
        "email": email,
        "name": name,
        "exp": expire,
        "iat": datetime.now(timezone.utc),
    }
    return jwt.encode(payload, settings.JWT_SECRET_KEY, algorithm=settings.JWT_ALGORITHM)


def decode_access_token(token: str) -> dict:
    try:
        return jwt.decode(token, settings.JWT_SECRET_KEY, algorithms=[settings.JWT_ALGORITHM])
    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token",
            headers={"WWW-Authenticate": "Bearer"},
        )


def get_current_user_id(
    credentials: HTTPAuthorizationCredentials = Depends(_bearer_scheme),
) -> str:
    """FastAPI dependency — extracts user_id from Bearer JWT."""
    payload = decode_access_token(credentials.credentials)
    return payload["sub"]


def get_current_user_email(
    credentials: HTTPAuthorizationCredentials = Depends(_bearer_scheme),
) -> str:
    payload = decode_access_token(credentials.credentials)
    return payload["email"]
